env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
overrides: []
parserOptions:
  project:
    - "tsconfig.json"
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - jsx-a11y
  - prettier
rules:
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  prettier/prettier: "error"
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
ignorePatterns:
  - ".eslintrc.yml"
  - "dist/"
  - "node_modules/"
  - "src-tauri/target"
